export const CART_ADD = 'CART_ADD';
export const CART_DELETE = 'CART_DELETE';
export const CART_COUNTER_INCREMENT = 'CART_COUNTER_INCREMENT';
export const CART_COUNTER_DECREMENT = 'CART_COUNTER_DECREMENT';
export const CART_SELECT = 'CART_SELECT';
export const CART_UNSELECT = 'CART_UNSELECT';
export const CART_SELECT_ALL = 'CART_SELECT_ALL';
export const CART_UNSELECT_ALL = 'CART_UNSELECT_ALL';

