export const CART_ADD = 'CART_ADD';
export const CART_DELETE = 'CART_DELETE';
export const CART_COUNTER_INCREMENT = 'CART_COUNTER_INCREMENT';
export const CART_COUNTER_DECREMENT = 'CART_COUNTER_DECREMENT';
